lib/apgdenwick_web/router.ex
defmodule APGDenwickWeb.Router do
  use APGDenwickWeb, :router

  pipeline :browser do
    plug(:accepts, ["html"])
    plug(:fetch_session)
    plug(:fetch_flash)
    plug(:protect_from_forgery)
    plug(:put_secure_browser_headers)
  end

  pipeline :api do
    plug(:accepts, ["json"])
  end

  scope "/", APGDenwickWeb do
    # Use the default browser stack
    pipe_through(:browser)

    get("/", PageController, :index)

    get("/sign-in", SignInController, :index)
    get("/sign-out", SignInController, :sign_out)

    get("/dashboard", DashboardController, :index)
    get("/dashboard/users", DashboardUserController, :index)
  end

  # Other scopes may use custom stacks.
  scope "/api", APGDenwickWeb do
    pipe_through(:api)

    post("/sign-in", SignInController, :sign_in, as: :api_sign_in)
    resources("/users", UserController, only: [:show, :index])
  end
end

lib/apgdenwick_web/views/layout_view.ex
defmodule APGDenwickWeb.LayoutView do
  use APGDenwickWeb, :view

  import APGDenwickWeb.Helpers
end

lib/apgdenwick_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>A.P.G. Denwick. Company Portfolio</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
  </head>

  <body>
    <div id="elm-wrapper">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script src="<%= static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/apgdenwick_web/templates/layout/dashboard.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>A.P.G. Denwick. Dashboard</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/dashboard.css") %>">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.13/css/all.css" integrity="sha384-DNOHZ68U8hZfKXOrtjWvjxusGo9WQnrNx2sqG0tfsghAvtVlRW3tvkXWZh58N9jp" crossorigin="anonymous">
  </head>

  <body>
    <div id="elm-wrapper" data-sign_in_path="<%= api_sign_in_path(@conn, :sign_in) %>"
      data-dashboard_path="<%= dashboard_path(@conn, :index) %>"
      data-sign_out_path="<%= sign_in_path(@conn, :sign_out)%>"
      data-after_sign_out_path="<%= sign_in_path(@conn, :index)%>"
      data-websocket_url="<%= apg_socket_url() %>">
      <%= render @view_module, @view_template, assigns %>
    </div>
    <script src="<%= static_path(@conn, "/js/dashboard.js") %>"></script>
  </body>
</html>

lib/apgdenwick_web/templates/layout/sign_in.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>A.P.G. Denwick. Sign In</title>
    <link rel="stylesheet" href="<%= static_path(@conn, "/css/sign_in.css") %>">
  </head>

  <body>
    <div id="elm-wrapper" data-sign_in_path="<%= api_sign_in_path(@conn, :sign_in) %>"
      data-dashboard_path="<%= dashboard_path(@conn, :index) %>"
      data-sign_out_path="<%= sign_in_path(@conn, :sign_out)%>"
      data-after_sign_out_path="<%= sign_in_path(@conn, :index)%>">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </body>
</html>